spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

